version: "3.8"
services:
  web:
    image: web
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "24678:24678"
    volumes:
      - ./:/app
      - /app/node_modules
    command: "npm run dev -- --host"